name: widget_preview_scaffold
description: Scaffolding for Flutter Widget Previews
publish_to: none
version: 0.0.1
environment:
  sdk: ^3.10.1
dependencies:
  flutter:
    sdk: flutter
  sketchbook_chat_box:
    path: ../..
flutter:
  uses-material-design: true
dependency_overrides:
  sketchbook_chat_box:
    path: ../..
